import type { AuthorizationStructure, ShareDataInstanceStructure } from './authorization-structures'
import type { RoleData } from './role'
import type { SocialAgentInvitationData } from './social-agent-invitation'

// ──────────────────────────
// Activity types (the outbox) — payload-contract-alignment (amended wire)
//
// One interface per activity RDF class (capitalized). `type` is the
// discriminant: the class tuple `['Activity', '<Class>', <as:*>]` — the
// values compact from the `dataModelContext` term definitions when framed.
// Fields are FLAT plain IRIs/literals on the wire (storage law: no
// `{ id, type }` ref objects in SPARQL-queried registries) — `XId` refs
// appear only in the temporal inputs the handler builds from these.
//
// The class's primary object rides as `as:object` in one of two forms
// (the object-embedding amendment — the inventory is the wire truth):
//  - live link — a single `as:object <iri>` triple (the resource exists or
//    is pre-minted via `iriForContained` and materialized by the workflow);
//  - snapshot — a minted `urn:uuid` node embedding the full POJO projection
//    inline in the activity graph (id known only at write; never
//    dereferenced — the singly-fetched activity doc already contains it).
// Parties (`admin`, `authorizationGrantee`, `peerId`, role members) ride the
// object — they are NOT flat fields; consumers read them from the embedded
// or linked POJO.
//
// `AuthorizationRequested`/`ShareRequested` stay flat (structure-based —
// candidates, NOT adopted; their fate — use or drop — is decided by
// authorization-granting.md Decision A, superseding the payload-contract
// followup reference).
// ──────────────────────────

type ActivityBase = {
  id: string
  /** plain IRI — the changed record/container, or (for ActivityCompleted)
   *  the completed activity IRI — storage law: no ref objects on the wire */
  target: string
  createdAt: string
}

/**
 * Embedded SocialAgentInvitation snapshot (the `InvitationAccepted` object —
 * minted `urn:uuid` node: `type` incl. `interop:SocialAgentInvitation`,
 * the opaque `capabilityUrl`, `label`, `note`). Never dereferenced.
 */
export type EmbeddedSocialAgentInvitation = {
  id: string
  type: string[]
  capabilityUrl: string
  label: string
  note?: string
}

/**
 * Embedded SocialAgentRegistration snapshot (the `AgentRegistrationAdded`
 * object — minted `urn:uuid` node: `type` incl.
 * `interop:SocialAgentRegistration`, `registeredAgent` — the peer,
 * `label`, `note`). Never dereferenced.
 */
export type EmbeddedSocialAgentRegistration = {
  id: string
  type: string[]
  registeredAgent: string
  label: string
  note?: string
}

/** Acceptance of a social agent invitation (acceptor's Activity Registry).
 *
 * `target` dropped (the InvitationCreated precedent): nothing consumes the
 * acceptor's registry-set id; the object is a self-contained urn:uuid
 * snapshot (the acceptor has no owning container to mint a real id in —
 * id-unknown-at-write keeps the snapshot form). */
export type InvitationAccepted = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'InvitationAccepted', 'as:Accept']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** urn:uuid snapshot of the invitation (opaque capabilityUrl inside) */
  object: EmbeddedSocialAgentInvitation
}

/**
 * Ref to the triggering `invitationAccepted` activity — id + class tuple
 * (the XId pattern for temporal inputs; refs stay TS-level, never on the
 * wire). Carried by the `acceptInvitation` workflow's completion.
 */
export type InvitationAcceptedId = {
  id: string
  type: InvitationAccepted['type']
}

/** Invitation created via RPC (activity-first step 1).
 *
 * Note (target dropped with the embedded-object form): the class has NO
 * `target` — the changed record's id rides `object.id` (the embedded pojo),
 * and the changed *container* (the invitation registry) is not consumed by
 * any dispatch/read path. The plan pins the same removal for the other
 * workflow-materialized classes as each step lands. */
export type InvitationCreated = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'InvitationCreated', 'as:Create']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /**
   * the invitation-to-be — full `SocialAgentInvitationData` projection minus
   * `capabilityUrl` (generated by the workflow at PUT time — never known to
   * the RPC/activity) and `registeredAgent` (accept-time only). The object is
   * named by the REAL pre-minted invitation id and carries `type` — the
   * storage-law read plane self-graph-filters (`FILTER(?g = ?s)`, sparql.md)
   * so the activity-graph type claim never surfaces as authoritative.
   */
  object: CreateInvitationPojo
}

/**
 * The invitation-to-be — the stored `SocialAgentInvitationData` POJO minus
 * the fields this workflow must not receive: `capabilityUrl` (generated in
 * the workflow/activity — the RPC must never know it early) and
 * `registeredAgent` (accept-time only, never set at creation). Also the
 * `as:object` of the `InvitationCreated` activity — the handler passes the
 * decoded object verbatim into the `createInvitation` workflow input.
 */
export type CreateInvitationPojo = Omit<
  SocialAgentInvitationData,
  'capabilityUrl' | 'registeredAgent'
>

/**
 * Ref to the triggering `invitationCreated` activity — id + class tuple
 * (the XId pattern for temporal inputs; refs stay TS-level, never on the
 * wire — the completed activity's type is still read from the resource).
 * Carried by the `createInvitation` workflow so the completion it writes is
 * traceable without dereferencing (activity-first step 1).
 */
export type InvitationCreatedId = {
  id: string
  type: InvitationCreated['type']
}

/** Reciprocal social agent registration written by the invitation handler.
 *
 * `target` dropped (the InvitationCreated precedent): the changed record's
 * id rides `object.id` — the REAL pre-minted registration id (the handler
 * pre-mints via `iriForContained`; the `establishReciprocal` workflow PUTs
 * the registration there and discovers the reciprocal). */
export type AgentRegistrationAdded = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'AgentRegistrationAdded', 'as:Add']
  /** as:actor — plain IRI (the session that wrote the registration) */
  actor: string
  /** real-id embedded projection of the registration-to-be — `registeredAgent`
   *  (the peer), `label`, `note` at the pre-minted id */
  object: EmbeddedSocialAgentRegistration
}

/**
 * Ref to the triggering `agentRegistrationAdded` activity — id + class
 * tuple (the XId pattern for temporal inputs). Carried by the
 * `establishReciprocal` workflow's completion.
 */
export type AgentRegistrationAddedId = {
  id: string
  type: AgentRegistrationAdded['type']
}

/** Admin authorization recorded (org context — activity-first step 5).
 * `target` dropped: the changed record's id rides `object.id`. The object
 * is a real-id embedded projection of the AdminAuthorization-to-be at the
 * PRE-MINTED id — the `addAdmin` workflow PUTs the resource there, then
 * grants + ACR rewrite, then completes (R1 re-decision: validation reads
 * stay in the RPC, the write moves to the workflow). */
export type AdminAuthorizationRecorded = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'AdminAuthorizationRecorded']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the AdminAuthorization-to-be — real-id embedded projection at the
   *  pre-minted id (never dereferenced — the workflow materializes it) */
  object: EmbeddedAdminAuthorization
}

/** Typed activity ref for the `addAdmin` workflow's completion — the XId
 * pattern for temporal inputs (refs stay TS-level, never on the wire). */
export type AdminAuthorizationRecordedId = {
  id: string
  type: AdminAuthorizationRecorded['type']
}

/**
 * Embedded AdminAuthorization — the full wire shape shared by the recorded
 * and revoked objects (real-id embedded projections at their ids, steps 5–6;
 * previously a urn:uuid snapshot). The admin's `grantee` rides inside either
 * way.
 */
export type EmbeddedAdminAuthorization = {
  id: string
  type: string[]
  grantee: string
  grantedBy: string
  scopeOfAuthorization: string
}

/** Admin authorization revoked (org context — activity-first step 6).
 * `target` dropped: the revoked record's id rides `object.id`. The object
 * is a real-id embedded projection of the EXISTING AdminAuthorization at its
 * real id (alive at write) — the `removeAdmin` workflow DELETEs it, revokes
 * grants + the ACR rewrite, then completes. The last-admin guard stays a
 * validation read in the RPC and is re-checked by `syncAdminAcr`. */
export type AdminAuthorizationRevoked = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'AdminAuthorizationRevoked']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the AdminAuthorization — real-id embedded projection at the EXISTING
   *  id (never dereferenced — the workflow deletes it) */
  object: EmbeddedAdminAuthorization
}

/** Typed activity ref for the `removeAdmin` workflow's completion — the XId
 * pattern for temporal inputs (refs stay TS-level, never on the wire). */
export type AdminAuthorizationRevokedId = {
  id: string
  type: AdminAuthorizationRevoked['type']
}

/**
 * Embedded request-structure snapshot (the denied `AuthorizationRecorded`
 * object — minted `urn:uuid` node). A denied authorization creates NO
 * DataAuthorization resource (`recordAuthorizationFromStructure` returns []
 * for `granted: false`), so there is nothing to link — the structure's
 * `grantee` rides here (parties ride the object); `hasAccessNeedGroup` is
 * carried for completeness. Only fields with dataModelContext terms survive
 * the wire (agentType/granted are not encoded — the grantee kind resolves in
 * the store and `granted: false` is implied by the snapshot's existence).
 * The granted form keeps the live-link DataAuthorization set.
 */
export type EmbeddedAuthorization = {
  id: string
  type: string[]
  grantee: string
  hasAccessNeedGroup?: string
}

/** Authorization recorded. `grantee` is read from the object — its kind is
 * resolved in the store (`getGrantees` routes by SPARQL), never baked into
 * the activity. */
export type AuthorizationRecorded = ActivityBase & {
  type: ['Activity', 'AuthorizationRecorded']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the AuthorizationRegistry */
  target: string
  /** granted: the DataAuthorizations — live-link set (one activity per
   *  grantee); denied (no resources are created): a urn:uuid snapshot of the
   *  request structure carrying `grantee` */
  object: string[] | EmbeddedAuthorization
}

/** Authorization revoked (grantee kind resolved in the store). */
export type AuthorizationRevoked = ActivityBase & {
  type: ['Activity', 'AuthorizationRevoked']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the AuthorizationRegistry */
  target: string
  /** the DataAuthorizations — live-link set (the workflow DELETEs them) */
  object: string[]
}

/**
 * Role membership changed — activity-first step 2 (the updateRole move).
 * `target` dropped (the InvitationCreated precedent): the changed role's id
 * rides `object.id`. The object is a real-id embedded projection of the
 * role-to-be (the full `RoleData` — the workflow loads the before-image,
 * PATCHes the role to this state and derives the affected diff from it; the
 * A-carrier member set is retired).
 */
export type RoleMembershipChanged = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'RoleMembershipChanged', 'as:Update']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the role-to-be — real-id embedded projection `{ id, type, label,
   *  members }` (the role exists at write; never dereferenced after) */
  object: RoleData
}

/** Typed activity ref for the `updateRole` workflow's completion — the XId
 * pattern for temporal inputs (refs stay TS-level, never on the wire; the
 * completed activity's type is still read from the resource). */
export type RoleMembershipChangedId = {
  id: string
  type: RoleMembershipChanged['type']
}

/** Role deleted (activity-first step 3). `target` dropped — the deleted
 * role's id rides `object.id`; the object is a real-id embedded projection
 * of the role-to-be-deleted (the full `RoleData`, alive at write) — the
 * write-time snapshot is the retry backstop: after a crash between the
 * DELETE and the completion, the role is gone and the member set would
 * otherwise be unrecoverable (the role-grantee authorizations are deleted
 * too), so the affected-set derivation uses the embedded members. */
export type RoleDeleted = Omit<ActivityBase, 'target'> & {
  type: ['Activity', 'RoleDeleted']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the role-to-be-deleted — real-id embedded projection `{ id, type,
   *  label, members }` (never dereferenced — the role disappears) */
  object: RoleData
}

/** Typed activity ref for the `deleteRole` workflow's completion — the XId
 * pattern for temporal inputs (refs stay TS-level, never on the wire). */
export type RoleDeletedId = {
  id: string
  type: RoleDeleted['type']
}

/** Peer mirror grants updated (reciprocal webhook). */
export type DelegatedGrantsUpdated = ActivityBase & {
  type: ['Activity', 'DelegatedGrantsUpdated']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the peer */
  target: string
  /** the reciprocal registration — live link */
  object: string
}

/** Authorization requested via RPC (future — activity-first step 2). */
export type AuthorizationRequested = ActivityBase & {
  type: ['Activity', 'AuthorizationRequested']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the requested authorization structure (plain-IRI fields only) */
  authorization: AuthorizationStructure
}

/** Resource sharing requested via RPC (future — activity-first step 3). */
export type ShareRequested = ActivityBase & {
  type: ['Activity', 'ShareRequested']
  /** as:actor — plain IRI (the registry owner) */
  actor: string
  /** the share request structure (plain-IRI fields only) */
  authorization: ShareDataInstanceStructure
  /** the sharing application — plain IRI */
  applicationId: string
}

/** Completion marker — no own fields; `target` is the completed activity IRI. */
export type ActivityCompleted = ActivityBase & {
  type: ['Activity', 'ActivityCompleted']
}

/**
 * The typed activity discriminant union — one member per activity RDF class.
 * Adding a class (the compile-time rule): extend this union, add the vocab
 * term + context entry; the handler, `reconcileActivities` and `events.ts`
 * each add their row to stay exhaustive.
 */
export type ActivityData =
  | InvitationAccepted
  | InvitationCreated
  | AgentRegistrationAdded
  | AdminAuthorizationRecorded
  | AdminAuthorizationRevoked
  | AuthorizationRecorded
  | AuthorizationRevoked
  | RoleMembershipChanged
  | RoleDeleted
  | DelegatedGrantsUpdated
  | AuthorizationRequested // candidate — flat carrier (authorization-granting.md: use or drop)
  | ShareRequested // candidate — flat carrier (authorization-granting.md: use or drop)
  | ActivityCompleted

/**
 * Whether the activity's `type` tuple contains the given class term
 * (`type[1]` — e.g. `'InvitationAccepted'`, or `'ActivityCompleted'`).
 * The typed union's per-member tuple literals make a bare `.includes` call
 * awkward to type, so the discriminant check lives here.
 */
export function isActivityClass(activity: ActivityData, cls: string): boolean {
  return (activity.type as readonly string[]).includes(cls)
}