name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - authorization-agent
          - application
          - data-model
          - utils
          - api-messages

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: yarn install --frozen-lockfile
      - run: npx lerna bootstrap
      - run: npx lerna run build

      - name: Create release
        working-directory: ./packages/${{ matrix.package }}
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEPLOYMENT_AUTH_TOKEN_NPM }}
